DROP ALL OBJECTS;


CREATE TABLE PUBLIC."ROLE" (
	VALUE VARCHAR(25) NOT NULL PRIMARY KEY,
);

INSERT INTO PUBLIC."ROLE" (VALUE) VALUES ('ADMIN');
INSERT INTO PUBLIC."ROLE" (VALUE) VALUES ('REDACTOR');
INSERT INTO PUBLIC."ROLE" (VALUE) VALUES ('VISITOR');


CREATE TABLE PUBLIC."USER" (
	ID_USER IDENTITY NOT NULL PRIMARY KEY,
	PSEUDO VARCHAR(25),
	LOGIN VARCHAR(25),
	PASSWORD VARCHAR(25),
	"ROLE" VARCHAR(25),
	CONSTRAINT USER_PK PRIMARY KEY (ID_USER)
);
ALTER TABLE PUBLIC."USER" ADD CONSTRAINT USER_ROLE_FK FOREIGN KEY ("ROLE") REFERENCES PUBLIC."ROLE"(VALUE) ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo01','login01','password01',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo02','login02','password02',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo03','login03','password03',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo04','login04','password04',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo05','login05','password05',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo06','login06','password06',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo07','login07','password07',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo08','login08','password08',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo09','login09','password09',NULL);
INSERT INTO PUBLIC."USER" (PSEUDO,LOGIN,PASSWORD,"ROLE") VALUES ('pseudo10','login10','password10',NULL);


CREATE TABLE PUBLIC.MESSAGE_TYPE (
	VALUE VARCHAR(25) NOT NULL PRIMARY KEY,
);

INSERT INTO PUBLIC.MESSAGE_TYPE (VALUE) VALUES ('PRIVATE');
INSERT INTO PUBLIC.MESSAGE_TYPE (VALUE) VALUES ('PUBLIC');


CREATE TABLE PUBLIC.MESSAGE (
	ID_MESSAGE IDENTITY NOT NULL PRIMARY KEY,
	ID_AUTHOR BIGINT NOT NULL,
	MESSAGE_TYPE VARCHAR(25) NOT NULL,
	CONTENT VARCHAR(25),
);
ALTER TABLE PUBLIC.MESSAGE ADD CONSTRAINT MESSAGE_MESSAGE_TYPE_FK FOREIGN KEY (MESSAGE_TYPE) REFERENCES PUBLIC.MESSAGE_TYPE(VALUE) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE PUBLIC.MESSAGE ADD CONSTRAINT MESSAGE_USER_FK FOREIGN KEY (ID_AUTHOR) REFERENCES PUBLIC."USER"(ID_USER) ON DELETE RESTRICT ON UPDATE RESTRICT;


CREATE TABLE PUBLIC.CONTACT (
	ID_CONTACT IDENTITY NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(25),
	LAST_NAME VARCHAR(25),
);

INSERT INTO PUBLIC.CONTACT (FIRST_NAME,LAST_NAME) VALUES ('first_name01','last_name01');


CREATE TABLE PUBLIC.PLAYER (
	ID_PLAYER IDENTITY NOT NULL PRIMARY KEY,
	ID_CONTACT_PARENT BIGINT,
	PSEUDO VARCHAR(25),
);
ALTER TABLE PUBLIC.PLAYER ADD CONSTRAINT PLAYER_CONTACT_FK FOREIGN KEY (ID_CONTACT_PARENT) REFERENCES PUBLIC.CONTACT(ID_CONTACT) ON DELETE RESTRICT ON UPDATE RESTRICT;

INSERT INTO PUBLIC.PLAYER (ID_CONTACT_PARENT,PSEUDO) VALUES (1,'pseudo01');
